version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src/laravel:/var/www/html:delegated
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src/laravel:/var/www/html:delegated
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    volumes:
      - mysql-data:/var/lib/mysql

  composer:
    build:
      context: .
      dockerfile: dockerfiles/composer.dockerfile
    volumes:
      - ./src/laravel:/var/www/html
    entrypoint: ["composer", "install"]

  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src/laravel:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']

  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ['npm']
    volumes:
      - ./src/laravel:/var/www/html

volumes:
  mysql-data:
